name: Pronto

on:
  - push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pronto Run
      uses: ./
      with:
        target: origin/main
        runners: >-
          rubocop bundler_audit brakeman yamllint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
